Replace static ChangeLog with dist-hook to generate from git log

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -157,3 +157,13 @@ shadows.DONE:
 	(for i in $(man_shadows:=.@APP_MAN_SUFFIX@) ; do \
 	 echo .so man$(APP_MAN_DIR_SUFFIX)/xtrap.$(APP_MAN_SUFFIX) > $$i; \
 	 done)
+
+EXTRA_DIST += ChangeLog
+MAINTAINERCLEANFILES = ChangeLog
+
+.PHONY: ChangeLog
+
+ChangeLog:
+	(GIT_DIR=$(top_srcdir)/.git git-log > .changelog.tmp && mv .changelog.tmp ChangeLog; rm -f .changelog.tmp) || (touch ChangeLog; echo 'git directory not found: installing possibly empty changelog.' >&2)
+
+dist-hook: ChangeLog
